### PR TITLE
Why a fork?

### PR DESCRIPTION
**Pull request by andre-hub**
When you will refactor the code, you can make it in the community branch.
Can i help you for this part?

### CODE REVIEW

**Comment by andre-hub** [comment]
Sorry you have no issue/question place

**Comment by d2r2** [comment]
Hi Andre! I have had only experience to publish pull request on github. I never create community branch on github. So, if you help me with this part it will be nice.

**Comment by d2r2** [comment]
@andre-hub, can you clarify your comment "Sorry you have no issue/question place"? Any additional action is required from my side before creation of community branch?

**Comment by andre-hub** [comment]
oh sorry. i mean the https://github.com/gotk3/gotk3 is for me the community branch.

you can create little changes and make pull requests to the master branch. after the review we can merge your changes. :-)

**Comment by d2r2** [comment]
Andre, thanks for clarification! Currently I am in the process of building desktop backup application (yet another), where I will use GUI based on fork. Give me week or two and I will get back with (as I hope) more stable version with some, as your describe, little changes :)

**Pull request closed without merging**
